language: python

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"

    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.4.4
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.1
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

before_install:
  # Remove oclint as it conflicts with GCC (indirect dependency of hdf5)
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;

      PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;
    fi

install:
  - pip install -U pip wheel
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - travis_wait pip install -U -e .[travis]

script:
  - flake8
  - autopep8 -r . --diff | tee check_autopep8
  - test ! -s check_autopep8
  - cd tests
  - pytest

sudo: false
